---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: data/_posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: data/_members
  label: Members
  create: documents
  match: "*.md"
  templates:
  - member
- type: directory
  path: data/_home
  label: Home
  create: none
  match: "*.md"
  templates:
  - home
- type: directory
  path: data/_about
  label: About
  create: none
  match: "*.md"
  templates:
  - services
- type: directory
  path: data/_timeline
  label: Timeline
  create: documents
  match: "*.md"
  templates:
  - timeline
- type: directory
  path: data/_projects
  label: Projects
  create: documents
  match: "*.md"
  templates:
  - projects
- type: directory
  path: data/_services
  label: Services
  create: none
  match: "*.md"
- type: directory
  path: data/_resources
  label: Resources
  create: documents
  match: "*.md"
  templates:
  - resource
- type: directory
  path: data/_iberian_bees
  label: Iberian bees
  create: none
  match: "*.md"
  templates:
  - iberian-bees
- type: directory
  path: data/_bees_guide
  label: Bees guide
  create: documents
  match: "*.md"
  templates:
  - bees-guide
upload_dir: public/assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".next"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
