---
label: Service
hide_body: true
fields:
- type: text
  name: title
  label: title
  config:
    required: true
- type: list
  name: items
  label: items
  config:
    required: true
- type: field_group
  name: button
  label: button
  config:
    required: true
  fields:
  - type: text
    name: url
    label: url
    config:
      required: true
  - type: text
    name: label
    label: label
    config:
      required: true
pages:
- data/_services/overview.md
